version: "3.2"
services:
  ch-server-1:
    image: yandex/clickhouse-server
    volumes:
      # - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      # - ./macros1.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/1:/var/lib/clickhouse
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
    ports:
      - 8123:8123
  ch-server-2:
    image: yandex/clickhouse-server
    volumes:
      # - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      # - ./macros2.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/2:/var/lib/clickhouse
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
  ch-server-3:
    image: yandex/clickhouse-server
    volumes:
      # - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      # - ./macros3.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./data/3:/var/lib/clickhouse
      - ./zookeeper.xml:/etc/clickhouse-server/config.d/zookeeper.xml
  ch-client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

  zookeeper1:
    image: zookeeper
    environment:
      ZOO_MY_ID: '1'
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg

  zookeeper2:
    image: zookeeper
    environment:
      ZOO_MY_ID: '2'
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg


  zookeeper3:
    image: zookeeper
    environment:
      ZOO_MY_ID: '3'
    volumes:
      - ./zoo.cfg:/conf/zoo.cfg

